---
title: "IBS_analyses"
author: "Hugo DENIS"
date: "2024-06-09"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Packages
```{r}
library(openxlsx)
library(dplyr)
library(ggplot2)
library(stringr)
library(RcppCNPy)
library(tidyr)
library(dendextend)
library(data.table)
```

#Load Identity by State Matrices 
```{r}
path='/nvme/disk0/lecellier_data/WGS_GBR_data/Analyses_outputs/IBS_results/'
outpath="/home/hdenis/Coral-Genomics/Figures/ANGSD_plot/"

meta=read.csv('/home/hdenis/Data/GBR_data/Coral colony metadata from the ECT1_RRAP_Aspathulata_2022.csv')

#Load IBS results from main cluster (northern/central GBR sites)
mat1=as.matrix(read.table(paste0(path,"GBR_aspat_group1_ibs05.ibsMat")))
list_file1=read.table('/nvme/disk0/lecellier_data/WGS_GBR_data/Aligned_files/aspat_bam_group1.filelist.txt',col.names='file')
list_file1$ID=paste0(sub("_.*", "",sub(".*2022-","",basename(list_file1$file))))
dimnames(mat1)=list(list_file1$ID,list_file1$ID)

#Load IBS results from second cluster (southern GBR sites)
mat2=as.matrix(read.table(paste0(path,"GBR_aspat_group2_ibs05.ibsMat")))
list_file2=read.table('/nvme/disk0/lecellier_data/WGS_GBR_data/Aligned_files/aspat_bam_group2.filelist.txt',col.names='file')
list_file2$ID=paste0(sub("_.*", "",sub(".*2022-","",basename(list_file2$file))))
dimnames(mat2)=list(list_file2$ID,list_file2$ID)

#Load IBS results for the Heron outlier cluster
matheout=as.matrix(read.table(paste0(path,"GBR_aspat_heron_outlier_group_ibs05.ibsMat")))
list_file3=read.table('/nvme/disk0/lecellier_data/WGS_GBR_data/Aligned_files/aspat_bam_heron_outlier.filelist.txt',col.names='file')
list_file3$ID=paste0(sub("_.*", "",sub(".*2022-","",basename(list_file3$file))))
dimnames(matheout)=list(list_file3$ID,list_file3$ID)

#technical replicates
cl1=c("Aspat-OCCH-1516-B","Aspat-OCCH-1516")
cl2=c("Aspat-STCR-750-B","Aspat-STCR-750")
```

#Perform hiearchical clustering (average method)
```{r}
hc1=hclust(as.dist(mat1),method="average") %>% as.dendrogram()

#Get average technical replicate threshold
replicate_threshold=max(mat1[cl1[2],cl1[1]],mat1[cl2[2],cl2[1]])


clones_color=rep("black",nrow(mat1))
clones_color[labels(hc1) %in% c(cl1,cl2)]="red"


#Only show labels of samples with high similarity 
mat_clones=mat1
mat_clones[mat_clones==0]<-NA
min=apply(mat_clones,2,function(x)min(x,na.rm=T))
clones_labels=labels(hc1)
min=min[order(match(names(min),clones_labels))]
names(min)[min>0.15]=""
clones_labels=names(min)

#Prevent overlap of labels
for(i in 2:length(clones_labels)){
  if(clones_labels[i-1]!="" & clones_labels[i]!=""){
    clones_labels[i]=paste0(clones_labels[i-1],"\n",clones_labels[i])
    clones_labels[i-1]=""
  }
}



png(paste0(outpath,"Group1_IBS_dendogram.png"),width=2000,height=1000,res=400)
par(mar=c(4,2.1,0.5,0.5))
hc1 %>% set("labels",clones_labels) %>% set("labels_cex",0.2) %>% hang.dendrogram() %>% assign_values_to_leaves_edgePar(value=clones_color,edgePar="col") %>% set("branches_lwd",0.5)  %>% plot(ylim=c(0.13,0.25),yaxt="n")
abline(h=replicate_threshold,col="red",lty=3)
abline(h=0.15,col="#2cb5c0",lty=3)
axis(2,cex.axis=0.5)
dev.off()
```

#Hiearchical clustering for second group
```{r}
hc2=hclust(as.dist(mat2),method="average") %>% as.dendrogram()

#Only show labels of samples with high similarity 
mat_clones2=mat2
mat_clones2[mat_clones2==0]<-NA
min2=apply(mat_clones2,2,function(x)min(x,na.rm=T))
clones_labels2=labels(hc2)
min2=min2[order(match(names(min2),clones_labels2))]
names(min2)[min2>0.15]=""
clones_labels2=names(min2)

#Prevent overlap of labels
for(i in 2:length(clones_labels2)){
  if(clones_labels2[i-1]!="" & clones_labels2[i]!=""){
    clones_labels2[i]=paste0(clones_labels2[i-1],"\n",clones_labels2[i])
    clones_labels2[i-1]=""
  }
}



png(paste0(outpath,"Group2_IBS_dendogram.png"),width=2000,height=1000,res=400)
par(mar=c(4,2.1,0.5,0.5))
hc2 %>% set("labels",clones_labels2) %>% set("labels_cex",0.2) %>% hang.dendrogram() %>% assign_values_to_leaves_edgePar(value="black",edgePar="col") %>% set("branches_lwd",0.5)  %>% plot(ylim=c(0.13,0.25),yaxt="n")
abline(h=replicate_threshold,col="red",lty=3)
axis(2,cex.axis=0.5)
abline(h=0.15,col="#2cb5c0",lty=3)
dev.off()
```

#Hiearchical clustering for heron outlier group
```{r}
hc3=hclust(as.dist(matheout),method="average") %>% as.dendrogram()

png(paste0(outpath,"Group3_IBS_dendogram.png"),width=2000,height=1000,res=400)
par(mar=c(4,2.5,0.5,0.5))
hc3  %>% set("labels_cex",0.5) %>% assign_values_to_leaves_edgePar(value="black",edgePar="col") %>% set("branches_lwd",1)  %>% plot(ylim=c(0,0.5),yaxt="n")
abline(h=replicate_threshold,col="red",lty=3)
axis(2,cex.axis=0.5)
abline(h=0.15,col="#2cb5c0",lty=3)
dev.off()
```

#Save list of putative clones 
```{r}
put_clones=data.frame()
mats=list(mat1,mat2)
for(i in 1:length(mats)){
  m=mats[[i]]
  for(j in 1:dim(m)[1]){
    for(k in 1:dim(m)[2]){
      if(m[j,k]<0.16 & j!=k){
        put_clones=rbind(put_clones,data.frame(Group=paste0("Group",as.character(i)),ID1=rownames(m)[j],ID2=colnames(m)[k],IBS=m[j,k]))
      }
    }
  }
}

put_clones=put_clones %>% distinct(IBS,.keep_all = T)
write.csv(put_clones,paste0(path,"putative_clones.csv"),row.names=F)

#Select one random samples per groups of putative clones custers
list_files=read.table('/nvme/disk0/lecellier_data/WGS_GBR_data/Aligned_files/aspat_bam_clean.filelist.txt',col.names='file')
list_files$ID=paste0(sub("_.*", "",sub(".*2022-","",basename(list_files$file))))

#Find group of colonies below 0.16 cutoff 
g1=cutree(hc1,h=0.16)
g2=cutree(hc2,h=0.16)

#Sample 1 random colony by group of putative clones (and remove technical replicates)
set.seed(123)
groups=data.frame(Group=c(rep("Group1",length(g1)),rep("Group2",length(g2))),Clone_clust=c(g1,g2),ID=c(names(g1),names(g2))) %>% subset(!ID %in% c("Aspat-OCCH-1516-B","Aspat-STCR-750-B")) %>% group_by(Group,Clone_clust) %>% slice_sample(n=1) %>% mutate(filter=1)

list_files_noclones=list_files %>% subset(!ID %in% groups$ID) %>% mutate(filter=0)

list_files_noclones=rbind(list_files_noclones %>% dplyr::select(ID,filter),groups %>% ungroup() %>% dplyr::select(ID,filter))
#Order in same order as original list files
list_files_noclones=list_files_noclones[match(list_files$ID,list_files_noclones$ID),]

#Save list of files without clones 
write.table(list_files_noclones %>% dplyr::select(filter),'/nvme/disk0/lecellier_data/WGS_GBR_data/Aligned_files/aspat_bam_noclones.filelist.txt',row.names=F,col.names = F,quote=F)
```


## Confirm clones using vcftools --relatedness 
method of Yang et al, Nature Genetics 2010 (doi:10.1038/ng.608)

#Read data 
```{r}
path='/nvme/disk0/lecellier_data/WGS_GBR_data/GATK_files/Vcf_files/'
outpath="/home/hdenis/Coral-Genomics/Figures/Pop_genetics_plots/"

#Load relatedness results
relat=fread(paste0(path,'aspat_clean_all_chr_SNP_filtered1.relatedness'),header=T)
relat$ID1=paste0(sub("_.*", "",sub(".*2022-","",basename(relat$INDV1))))
relat$ID2=paste0(sub("_.*", "",sub(".*2022-","",basename(relat$INDV2))))

cl1=c("Aspat-OCCH-1516-B","Aspat-OCCH-1516")
cl2=c("Aspat-STCR-750-B","Aspat-STCR-750")

group1=fread(paste0(path,'aspat_bam_group1.filelist.txt'),header=F,col.names="file")
group1$ID=paste0(sub("_.*", "",sub(".*2022-","",basename(group1$file))))
group2=fread(paste0(path,'aspat_bam_group2.filelist.txt'),header=F,col.names="file")
group2$ID=paste0(sub("_.*", "",sub(".*2022-","",basename(group2$file))))
```


#Perform hierarchical clustering
```{r}
mat1=relat %>% subset(ID1 %in% group1$ID & ID2 %in% group1$ID)
mat1=mat1[,c("ID1","ID2","RELATEDNESS_AJK")]
mat1=dcast(mat1,ID1~ID2,drop=F)
mat1=data.frame(mat1)
rownames(mat1)=mat1$ID1
mat1=mat1[,-1]
colnames(mat1)=rownames(mat1)

mat1=1-mat1

mat1[lower.tri(mat1)]=t(mat1[upper.tri(mat1)])

mat1=mat1[1:423,1:423]
#Reverse order of metric such as closest individuals as the smallest distance

hc1=hclust(dist(as.matrix(mat1)),method="average") %>% as.dendrogram()

#Get average technical replicate threshold
replicate_threshold=max(mat1[cl1[2],cl1[1]],mat1[cl2[2],cl2[1]])


clones_color=rep("black",nrow(mat1))
clones_color[labels(hc1) %in% c(cl1,cl2)]="red"


#Only show labels of samples with high similarity 
mat_clones=mat1 %>% replace(.,col(.)==row(.),NA)
min=apply(mat_clones,2,function(x)min(x,na.rm=T))
clones_labels=labels(hc1)
min=min[order(match(names(min),clones_labels))]
names(min)[min>0.2]=""
clones_labels=names(min)

# 
# max=apply(mat_clones,2,function(x)max(x,na.rm=T))
# clones_labels=labels(hc1)
# max=max[order(match(names(max),clones_labels))]
# names(max)[max<0.1]=""
# clones_labels=names(max)

#Prevent overlap of labels
for(i in 2:length(clones_labels)){
  if(clones_labels[i-1]!="" & clones_labels[i]!=""){
    clones_labels[i]=paste0(clones_labels[i-1],"\n",clones_labels[i])
    clones_labels[i-1]=""
  }
}


library(dendextend)
png(paste0(outpath,"Group1_relatedness_dendogram.png"),width=2000,height=1000,res=400)
par(mar=c(4,2.1,0.5,0.5))
hc1 %>% dendextend::set("labels",clones_labels) %>% dendextend::set("labels_cex",0.2) %>% dendextend::hang.dendrogram() %>% dendextend::assign_values_to_leaves_edgePar(value=clones_color,edgePar="col") %>% dendextend::set("branches_lwd",0.5)  %>% plot(ylim=c(0.7,1.5),yaxt="n")
# hc1 %>% dendextend::set("labels",clones_labels) %>% dendextend::set("labels_cex",0.2) %>% dendextend::hang.dendrogram() %>% dendextend::assign_values_to_leaves_edgePar(value=clones_color,edgePar="col") %>% dendextend::set("branches_lwd",0.5)  %>% plot(ylim=c(0,1),yaxt="n")
abline(h=replicate_threshold,col="red",lty=3)
axis(2,cex.axis=0.5)
dev.off()
```

